global:
  scrape_interval:     10s # 默认抓取周期
#  external_labels:
#    monitor: 'codelab-monitor'
scrape_configs:
#  - job_name: 'node-exporter' #服务的名称
#    scrape_interval: 5s
#    metrics_path: /metrics  #获取指标的url
#    static_configs:
#            - targets: ['172.19.1.100:9100'] # 这个为监听指定服务服务的ip和port，需要修改为自己的ip，貌似云服务必须用公网ip
  - job_name: 'locust'
    scrape_interval: 1s
    metrics_path: '/export/prometheus'
    static_configs:
      - targets: ['192.168.3.94:8089']
        labels:
          instance: locust
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          instance: prometheus