version: '3'
services:
  redis:
    image: redis:latest
    container_name: lbk-redis
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/data/docker-home/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - /root/data/docker-home/redis/logs:/logs
    ports:
      - "6379:6379"
    restart: always